spring.application.name=system-deployment-project-api

# Datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:implantation_db}
spring.datasource.username=${DB_USER:implantation_user}
spring.datasource.password=${DB_PASSWORD:implantation_pass}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
